//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Состав_заказа = new HashSet<Состав_заказа>();
        }
    
        public long id_Товара { get; set; }
        public string Артикул { get; set; }
        public string Наименование_товара { get; set; }
        public string Единица_измерения { get; set; }
        public decimal Стоимость { get; set; }
        public double Размер_макс_возм_скидки { get; set; }
        public string Производитель { get; set; }
        public long id_Поставщика { get; set; }
        public long id_Категории_товара { get; set; }
        public double Действующая_скидка { get; set; }
        public int Кол_во_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    
        public virtual Категории_товара Категории_товара { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_заказа> Состав_заказа { get; set; }
    }
}
